export const CREATE_SESSION = 'CREATE_SESSION'
export const SET_PAGE_NAME = 'SET_PAGE_NAME'
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION'

export const LOGIN = 'LOGIN'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

export const UPDATE_SESSIONS = 'UPDATE_SESSIONS'
